create_docker_compose() {
  echo -e "${YELLOW}Creant docker-compose.yml...${NC}"
  mkdir -p /opt/wordpress
  cd /opt/wordpress

  cat > docker-compose.yml <<EOF
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "$WP_PORT:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME

volumes:
  db_data:
  wp_data:
EOF

  echo -e "${GREEN}Fitxer docker-compose.yml creat a /opt/wordpress.${NC}"
}

create_docker_compose
